### ISSUE TITLE
Mouse resets if object selection fails to go through

### ISSUE THREAD

**Issue by Withaust** [bbbscarter/GodotRuntimeDebugTools#1]
Currently, mouse would randomly reset to the center of the screen if none of the physics objects could be picked. This is really annoying to the point that this should be considered a bug.

**Comment by bbbscarter** [comment]
Curious - I've not seen that, but it could be related to the way the rest of the client application handles input; unfortunately there's no way of guaranteeing mouse clicks aren't processed elsewhere in a client app.

I've just pushed a new (highly refactored) version of the package on Github (but not on the Asset Lib index yet). I can't reproduce the behaviour in the latest version in the example scene. Let me know if this fixes it for you.
