### ISSUE TITLE
Keeping the initial mouse mode when switching back to the character camera

### ISSUE THREAD

**Issue by GonnaFlyMethod** [bbbscarter/GodotRuntimeDebugTools#4]
**Short description of the problem:**
When switching back from Debug3D camera to Main Character camera, the mouse input mode is not preserved.

**Full description:**
I'm testing the game in windowed mode, when I start it from the engine's editor, the mouse is entirely hidden. 
```csharp
Input.MouseMode = Input.MouseModeEnum.Captured;  // This is specified by me in script
```
then, I do ALT + TAB to quickly navigate to godot and hit RDT (3D Debug camera). After that, I'm switching back to Character camera (FPS camera) by unchecking 3D Debug camera in RDT, and the mouse is visible, and because of it, when I want to rotate a character, the character rotates as long as the mouse cursor is presented in the game window, if the cursor exits from the window frame, then the character stops rotating. My proposal is to preserve the mouse input mode when switching back to the Character camera from 3D Debug camera. 

The showcase of the problem (after switching from 3D Debugging camera to Character Camera):

https://github.com/user-attachments/assets/a722385e-5075-45ca-a441-cd08e4c75f68

> [!NOTE]  
> Also, I've tried the full screen mode when play testing, and there's the same behavior: the cursor is always showed up. The same true for switching from 2D Debugging to main Character camera.

**Comment by GonnaFlyMethod** [comment]
@bbbscarter hey. I've finished the logic related to preserving mouse mode and I would like to create pull request. But for now I don't have rights to push my changes

![image](https://github.com/user-attachments/assets/f4a2a2ab-ea9e-4880-949e-79566965f2a9)

**Comment by bbbscarter** [comment]
This is correct - as the maintainer, only I've got push rights.

Have you followed the standard process for [pull requests](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request)? If so, once you create the request I can review the changes and then merge them.

**Comment by GonnaFlyMethod** [comment]
👋 here's the [pull request](https://github.com/bbbscarter/GodotRuntimeDebugTools/pull/5)

**Comment by bbbscarter** [comment]
Thanks for doing this! Will review when I get a chance.

**Comment by GonnaFlyMethod** [comment]
@bbbscarter  Hey, I'm proposing to close this issue, what do you think?

**Comment by bbbscarter** [comment]
Yes, agreed.
